title: Official Media Bias/Fact Check Extension
tagline: Homepage
markdown: kramdown
layout: default
comments: true
disqus: mbfcext

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
description:         'Homepage of the Official Media Bias/Fact Check Extension.'
url:                 https://drmikecrowe.github.io/mbfcext/
baseurl:             ''

# About/contact
author:
  name:              Mike Crowe
  url:               https://github.com/drmikecrowe
  email:             drmikecrowe@gmail.com

github:
  repo:           github.com/drmikecrowe/mbfcext
# Custom vars
version:             1.0.0

pages_list:
  "Beta!": 'https://drmikecrowe.github.io/mbfcext/beta'

extension_list:
  "Production Extension": https://chrome.google.com/webstore/detail/official-media-biasfact-c/ganicjnkcddicfioohdaegodjodcbkkh
  "Beta Extension": https://chrome.google.com/webstore/detail/betaofficial-media-biasfa/janhmnkcmhhbkachkhmchiidolkpeafm