title: Official Media Bias/Fact Check Extension
tagline: Homepage for the Google Chrome extension
markdown: kramdown
layout: default
comments: true
disqus: mbfcext

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://drmikecrowe.github.io/mbfcext/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mike Crowe
  url:               https://github.com/drmikecrowe
  email:             drmikecrowe@gmail.com

# Custom vars
version:             1.0.0

theme: jekyll-theme-tactile